const express = require("express");
const router = express.Router();

const CompanyRouter = require("./companyName.routes");
const StaffRouter = require("./staff.routes");
const AccountMasterRouter = require("./accountMaster.routes");
const AssignTaskRouter = require("./assignTask.routes");
const Order = require("./order.routes");
const Lead = require("./lead.routes");
const Purchase = require("./purchase.routes");
const productItem = require("./productItem.routes");
const Inventory = require("./inventory.routes");
const fileUpload = require("./filesUpload.routes");
const status =  require("./status.routes");
const Roles = require("./role.routes");
const filedownloadRouter = require("./fileDownload.routes");
const MaterialRouter = require("./material.routes");
const RoleDepartmentRouter = require("./roleDepartment.routes");
const RoleDepartmentCompanyRouter = require("./roleDepartmentCompany.routes");
const performanceInvoiceRoutes = require("./performanceInvoice.route");
const Vendor = require("./vendor.routes");
const ImportHistory = require("./importHistory.routes");
const Quotation = require("./quotation.routes");
const Bom = require("./bom.routes");
const JobCard = require("./jobCard.routes");
const Machine = require("./machine.routes");
const StockLedger = require("./stockLedger.routes");
const Rfq = require("./rfq.routes");
const PurchaseOrder = require("./purchaseOrder.routes");
const Grn = require("./grn.routes");
const Invoice = require("./invoice.routes");
const Receipt = require("./receipt.routes");
const VendorPayment = require("./vendorPayment.routes");
const Costing = require("./costing.routes");
const Notification = require("./notification.routes");
const Approval = require("./approval.routes");
const Dashboard = require("./dashboard.routes");

router.use("/company", CompanyRouter);
router.use("/staff", StaffRouter);
router.use("/account-master", AccountMasterRouter);
router.use("/assign-task", AssignTaskRouter);
router.use("/orders", Order);
router.use("/lead", Lead);
router.use("/purchase", Purchase);
router.use("/inventory", Inventory);
router.use("/vendor", Vendor);
router.use("/productItem", productItem);
router.use("/fileUpload",fileUpload);
router.use("/status",status);
router.use("/role",Roles);
router.use("/filedownload",filedownloadRouter);
router.use("/material",MaterialRouter);
router.use("/roleDepartment",RoleDepartmentRouter);
router.use("/roleDepartmentCompany",RoleDepartmentCompanyRouter);
router.use("/performance-invoice", performanceInvoiceRoutes);
router.use("/import-history", ImportHistory);
router.use("/quotations", Quotation);
router.use("/boms", Bom);
router.use("/job-cards", JobCard);
router.use("/machines", Machine);
router.use("/stock-ledger", StockLedger);
router.use("/rfqs", Rfq);
router.use("/purchase-orders", PurchaseOrder);
router.use("/grns", Grn);
router.use("/invoices", Invoice);
router.use("/receipts", Receipt);
router.use("/vendor-payments", VendorPayment);
router.use("/costing", Costing);
router.use("/notifications", Notification);
router.use("/approvals", Approval);
router.use("/dashboard", Dashboard);
module.exports = router;
